- configuration/pih/pih-config-mexico-capitan.json
- configuration/pih/pih-config-mexico-demo.json
- configuration/pih/pih-config-mexico-honduras.json
- configuration/pih/pih-config-mexico-laguna.json
- configuration/pih/pih-config-mexico-letrero.json
- configuration/pih/pih-config-mexico-matazano.json
- configuration/pih/pih-config-mexico-plan.json
- configuration/pih/pih-config-mexico-production.json
- configuration/pih/pih-config-mexico-reforma.json
- configuration/pih/pih-config-mexico-salvador.json
- configuration/pih/pih-config-mexico-soledad.json
- configuration/pih/pih-config-mexico.json
https://pihemr.atlassian.net/browse/UHM-4683
@mogoodrich if you wouldn't mind taking a look to make sure this is sort of what you were envisioning
> UHM-4683 Move Location Tag Setup out of PIH Core and into Config

- configuration/globalproperties/gp_ces.xml
Let's set this back to the default, it's helpful when debugging...
> change log level to info

- configuration/pih/pih-config-mexico-demo.json
- configuration/pih/pih-config-mexico-production.json
https://pihemr.atlassian.net/browse/MEX-495
depends on https://github.com/PIH/openmrs-module-pihcore/pull/201
> Add Casa Materna and CER locations for CES

- configuration/pih/pih-config-mexico.json
They were evidently forgotten from https://github.com/PIH/openmrs-config-ces/pull/10
> Add the rest of location tags to Casa Materna and CER

- configuration/pih/htmlforms/consult.xml
https://pihemr.atlassian.net/browse/MEX-494
Following https://stackoverflow.com/a/12997207/1464495 and the [linked Fiddle](https://jsfiddle.net/jdavidzapatab/6sctvg2z/)
> Fix the print Rx button for latest chrome compat

- configuration/pih/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-357
> MEX-357 Should be able to mark patient as dead

- configuration/pih/pih-config-mexico-demo.json
https://pihemr.atlassian.net/browse/MEX-357
> MEX-357: Add markPatientDead component to ces-ci (mexico-demo)

- configuration/pih/htmlforms/consult.xml
Based on work from https://pihemr.atlassian.net/browse/UHM-5390
Before
After
> Don't show retired drugs in drug list

- configuration/reports/reportdescriptors/dataexports/cesMeds.yml
- configuration/reports/reportdescriptors/dataexports/sql/cesMeds.sql
@mogoodrich  or @brandones - whichever of you can get to this sooner...
> UHM-5474: Migrate CES medications report to config-ces

- configuration/reports/reportdescriptors/dataexports/sql/mexicoCesMeds.sql
> Medicamentos con cantidad 0

- configuration/pih/htmlforms/consult.xml
> Correcion de error de impresion de receta

- configuration/pih/htmlforms/consult.xml
- configuration/pih/htmlforms/vitals.xml
> Traducciones

- configuration/pih/htmlforms/consult.xml
- configuration/pih/scripts/global/ces.js
This fixes https://pihemr.atlassian.net/browse/UHM-5375 for Mexico. It puts all Javascript into a Javascript file. Much of it is just moved; however, the code for gestational age and EDD calculation has been updated to bring it in alignment with https://pihemr.atlassian.net/browse/UHM-5676 .
> Move htmlform JS into its own file (UHM-5375)

- configuration/pih/htmlforms/consult.xml
- configuration/pih/scripts/global/ces.js
Depends on https://github.com/PIH/openmrs-config-pihemr/pull/257
> Use generic form expanding function for medications

- configuration/pih/htmlforms/clinicalHistory.xml
Reverts PIH/openmrs-config-ces#55
At @Joseph-Developer 's request. The original PR was not marked as a draft, but should have been.
> Revert "History clinical"

- configuration/pih/petl/datasources/openmrs-capitan.yml
- configuration/pih/petl/datasources/openmrs-cesProd.yml
- configuration/pih/petl/datasources/openmrs-honduras.yml
- configuration/pih/petl/datasources/openmrs-laguna.yml
- configuration/pih/petl/datasources/openmrs-letrero.yml
- configuration/pih/petl/datasources/openmrs-matazano.yml
- configuration/pih/petl/datasources/openmrs-monterrey.yml
- configuration/pih/petl/datasources/openmrs-plan.yml
- configuration/pih/petl/datasources/openmrs-planAlta.yml
- configuration/pih/petl/datasources/openmrs-reforma.yml
- configuration/pih/petl/datasources/openmrs-salvador.yml
- configuration/pih/petl/datasources/openmrs-soledad.yml
- configuration/pih/petl/datasources/warehouse.yml
- configuration/pih/petl/jobs/create-partitions.yml
- configuration/pih/petl/jobs/create-source-views-and-functions.yml
- configuration/pih/petl/jobs/import-to-table-partition.yml
- configuration/pih/petl/jobs/refresh-base-tables.yml
- configuration/pih/petl/jobs/refresh-openmrs-data.yml
- configuration/pih/petl/jobs/sql/extractions/test_encounter.sql
- configuration/pih/petl/jobs/sql/schemas/test_encounter.sql
- configuration/pih/petl/jobs/sql/utils/context.sql
- configuration/pih/petl/jobs/sql/utils/create-partitions-if-needed.sql
- configuration/pih/petl/jobs/sql/utils/create_views.sql
https://pihemr.atlassian.net/browse/MEX-513
> MEX-513 Add minimal required ETL job to PETL to test process and configuration

- configuration/frontend/config.json
@brandones if you can add in the configuration property around published forms, we can add it to the config here before merging.
> UHM-6390: Pilot Html Forms in O3

- configuration/pih/htmlforms/clinicalHistory.xml
Made possible by https://pihemr.atlassian.net/browse/UHM-6366
> Make family history section use checkboxes

- configuration/locations/locations.csv
- configuration/pih/pih-config-mexico-demo.json
- configuration/pih/pih-config-mexico-production.json
Puse tambien en el demo para poder ver el cambio
> New location for pediatrics

- configuration/pih/htmlforms/consult.xml
- configuration/pih/scripts/global/ces.js
[MEX-517](https://pihemr.atlassian.net/browse/MEX-517)
> MEX-517  Auto update program status from form

- configuration/programs/programs.csv
> LIB-325 Added order to programs
